routes/user.php
<?php

use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::prefix('admin/users')->group(function (){
    Route::controller(UserController::class)->group(function (){
        Route::as('user.')->group(function (){
            Route::get('/list','index')->name('index')
                ->middleware('permission:user.index');
            Route::get('/active-user/{id}','active')->name('active');
            Route::get('/inactive-user/{id}','inactive')->name('inactive');
            Route::delete('/{id}','destroy')->name('destroy')
            ->middleware('permission:user.destroy');
            Route::get('/create','create')->name('create')
            ->middleware('permission:user.create');
            Route::post('/create/user','store')->name('store')
            ->middleware('permission:user.create');
            Route::get('/update/{id}','edit')->name('edit')
            ->middleware('permission:user.update');
            Route::put('update/user/{id}','update')->name('update')
            ->middleware('permission:user.update');
            Route::get('/show/{id}','show')->name('show')
            ->middleware('permission:user.show');
            Route::get('/search-list','userListAjax')->name('userListAjax');
            Route::get('/search-user','search')->name('search');
        });
    });
});

routes/web.php
<?php
foreach (File::allFiles(__DIR__ ) as $route_file) {
    (basename($route_file =='web.php')) ? : (require_once $route_file);
}

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Casts\Attribute;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;


    const ROLE_ADMIN = 'Admin';
    const PATH_IMAGE = 'images/users/';
    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'image',
        'email',
        'password',
        'gender',
        'activated'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    protected function image(): Attribute
    {
        return Attribute::make(
            get: fn($image) =>
            (empty($image)) ? null : ((\Illuminate\Support\Str::of($image)->isMatch('/http(.*)/')) ?  $image : self::PATH_IMAGE . $image)
        );

    }

    public function roles(): BelongsToMany
    {
        return $this->belongsToMany(Role::class, 'roles_users', 'user_id', 'role_id');
    }

    public function hasPermission($permission): bool
    {
        if ($this->isAdmin()){
            return true;
        }
        foreach ($this->roles as $role){
            if ($role->hasPermission($permission)){
                return true;
            }
        }
        return false;
    }

    public function hasRole($name)
    {
        return $this->roles->pluck('name')->contains($name);
    }

    public function isAdmin(){
        return $this->hasRole(self::ROLE_ADMIN);
    }


    public function scopeOrWithName($query, $name)
    {
        return empty($name) ? $query : $query->orWhereFullText('name', $name);
    }

    public function scopeOrWithEmail($query, $email)
    {
        return empty($email) ? $query : $query->orWhereFullText('email', $email);
    }

}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\StoreRequest;
use App\Http\Requests\Users\UpdateRequest;
use App\Service\UserService;
use Illuminate\Http\Request;

class UserController extends Controller
{

    protected UserService $userService;

    /**
     * @param  UserService  $userService
     */
    public function __construct(UserService $userService)
    {
        $this->userService = $userService;
    }

    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $users = $this->userService->index();
        return view('admin.user.list', compact('users'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return response()->json([
            'form' => view('admin.user.create')->render()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(StoreRequest $request)
    {
        $this->userService->store($request);
        $users = $this->userService->index();
        return response()->json([
            'table' => view('admin.user.paginate', compact('users'))->render()
        ]);
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $user = $this->userService->show($id);
        return response()->json([
            'form' => view('admin.user.show',compact('user'))->render()
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $user= $this->userService->edit($id);
        $roles = $this->userService->roleRepository->latest('id')->get();
        return response()->json([
            'form' => view('admin.user.edit',compact('user','roles'))->render()
        ]);
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(UpdateRequest $request, string $id)
    {
        $this->userService->update($request,$id);
        $users = $this->userService->index();
        return response()->json([
            'table' => view('admin.user.paginate', compact('users'))->render()
        ]);
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $this->userService->delete($id);
        $users = $this->userService->index();
        return response()->json([
            'table' => view('admin.user.paginate', compact('users'))->render()
        ]);
    }

    public function active(string $id)
    {
        $this->userService->active($id);
        return redirect()->route('user.index');
    }

    public function inactive(string $id)
    {
        $this->userService->inactive($id);
        return redirect()->route('user.index');
    }

    public function userListAjax()
    {
        return $this->userService->userListAjax();
    }

    public function search(Request $request){
        $users = $this->userService->search($request->name);

        return response()->json([
            'table' => view('admin.user.paginate',compact('users'))->render()
        ]);
    }
}

resources/views/admin/user/create.blade.php
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Create User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('user.store')}}" method="post" enctype="multipart/form-data" id="form-data">
                    @csrf
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">UserName</label>
                        <input type="text" class="form-control" value="" name="name" id="name">
                        <span id="name-error" class="error invalid-feedback"></span>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Image</label>
                        <input type="file" class="form-control" value="" name="image" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Email</label>
                        <input type="text" min="0" class="form-control" value="" name="email" id="email">
                        <span id="email-error" class="error invalid-feedback"></span>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Password</label>
                        <input type="password" min="0" class="form-control" value="" name="password" id="password">
                        <span id="password-error" class="error invalid-feedback"></span>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Gender</label>
                        <select name="gender" class="form-control form-control-sm" id="gender">
                                <option value="0">Male</option>
                                <option value="1">Female</option>
                        </select>
                        <span id="gender-error" class="error invalid-feedback"></span>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success" id="submit">Create</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

resources/views/admin/user/edit.blade.php
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Update User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form action="{{route('user.update',$user->id)}}" method="post" enctype="multipart/form-data" id="form-data">
                    @csrf
                    @method('PUT')
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">UserName</label>
                        <input type="text" class="form-control" value="{{$user->name}}" name="name" id="name">
                        <span id="name-error" class="error invalid-feedback"></span>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Image</label> <br>
                        <img src="{{ getImage($user->image) }}" alt=""
                             class="img-thumbnail img-circle">
                        <input type="file" class="form-control" name="image" id="recipient-name">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Email</label>
                        <input type="text" min="0" class="form-control" value="{{$user->email}}" name="email" id="email">
                        <span id="email-error" class="error invalid-feedback"></span>
                    </div>

                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Permission</label>
                        <div class="form-check">
                            @foreach($roles as $role)
                                <input name="roles[]" type="checkbox"  value="{{$role->id}}" id="{{$role->id}}"
                                @foreach($user->roles as $item)
                                    @checked($role->id === $item->id)
                                    @endforeach
                                >
                                <label for="{{ $role->id }}">{{$role->name}}</label>
                                <br>
                            @endforeach
                        </div>
                    </div>

{{--                    <div class="form-group">--}}
{{--                        <label for="recipient-name" class="col-form-label">Roles</label>--}}
{{--                        @foreach($user->roles as $role)--}}
{{--                            <li >{{$role->name}}</li>--}}
{{--                        @endforeach--}}
{{--                        <select name="roles[]" multiple="multiple" class="form-control form-control-sm" id="roles[]">--}}
{{--                            <option value="">---->Select roles<----</option>--}}
{{--                            @foreach($roles as $role)--}}
{{--                                <option value="{{$role->id}}">{{$role->name}}</option>--}}
{{--                            @endforeach--}}
{{--                        </select>--}}
{{--                        <span id="category-error" class="error invalid-feedback"></span>--}}
{{--                    </div>--}}
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Gender</label>
{{--                        @php--}}
{{--                             if ($user->gender == 0){--}}
{{--                                 echo '<li>Male</li>';--}}
{{--                             }--}}
{{--                             else{--}}
{{--                                 echo '<li>Female</li>';--}}
{{--                             }--}}
{{--                        @endphp--}}
                        <br>
                        <select name="gender" class="form-control form-control-sm" id="exampleFormControlSelect3">
                            <option value="0" {{$user->gender == 0 ? 'selected':''}}>Male</option>
                            <option value="1" {{$user->gender == 1 ? 'selected':''}}>Female</option>
                        </select>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-success" id="submitUpdate">Update</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>

resources/views/admin/user/list.blade.php
@extends('layouts.app')

@section('content')
    @hasPermission('user.index')
    <div class="content-wrapper">
        <div class="form-group">
            <form onsubmit="return false;" action="{{route('user.search')}}" method="GET" enctype="multipart/form-data" id="form-search">
                @csrf
                @method('GET')
                <div class="input-group">
                    <input type="search" id="search_user" name="name" class="form-control" placeholder="Recipient's username" aria-label="Recipient's username" aria-describedby="basic-addon2">
                </div>
            </form>
        </div>
        <div class="page-header">
            <h3 class="page-title"> List User </h3>
            @hasPermission('user.create')
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <button type="button" class="btn btn-primary open-modal" onclick="javascript:void(0)" href="{{route('user.create')}}">Create</button>
{{--                    <a class="open-modal" onclick="javascript:void(0)" href="{{route('user.create')}}">Create</a>--}}
                </ol>
            </nav>
            @endhasPermission
        </div>

        <div id="table">
            @include('admin.user.paginate')
        </div>

        <div id="modal"></div>

    </div>
    @endhasPermission
@endsection

resources/views/admin/user/paginate.blade.php
<table class="table">
    <thead class="table table-dark">
    <tr>
        <th> ID</th>
        <th> Name</th>
        <th> Image</th>
        <th> Email</th>
        <th> Gender</th>
        <th> Activated</th>
        <th> Action</th>
    </tr>
    </thead>
    <tbody class="table table-warning">
    @if($users->isNotEmpty())
    @foreach($users as $user)
        <tr>
            <td> {{$user->id}}</td>
            <td> {{$user->name}}</td>
            <td>
                <img src="{{ getImage($user->image) }}" alt=""
                     class="img-thumbnail img-circle">
            </td>
            <td> {{$user->email}}</td>
            <td>
                @php
                     if ($user->gender == 0){
                         echo 'Male';
                     }
                     else{
                         echo 'Female';
                     }
                @endphp
            </td>
            <td>
                @php
                    if ($user->activated == 0){
                @endphp
                <a href="{{route('user.active',$user->id)}}" onclick="javascript:void(0)" class="btnActive"><span class="fa-thumb-styling fa fa-thumbs-down"></span></a>
                @php
                    }else{
                @endphp
                <a href="{{route('user.inactive',$user->id)}}" onclick="javascript:void(0)" class="btnActive"><span class="fa-thumb-styling fa fa-thumbs-up" ></span></a>

                @php
                    }
                @endphp
            </td>
            <td>
                @hasPermission('user.show')
                <a href="{{route('user.show',$user->id)}}" class="open-modal" onclick="javascript:void(0) " title="View Student">
                    <button class="btn btn-info btn-sm btn-info" data-toggle="modal">
                        <i class="fa fa-eye" aria-hidden="true"></i>
                    </button>
                </a>
                @endhasPermission

                @hasPermission('user.update')
                <a href="{{route('user.edit',$user->id)}}" class="open-modal" onclick="javascript:void(0) " title="View Student">
                    <button class="btn btn-info btn-sm btn-secondary" data-toggle="modal">
                        <i class="fa fa-edit" aria-hidden="true"></i>
                    </button>
                </a>
                @endhasPermission

                @hasPermission('user.destroy')
                <a href="{{route('user.destroy',$user->id)}}" onclick="javascript:void(0)" class="btnDelete" title="View Student">
                    <button class="btn btn-info btn-sm btn-danger btn-open-modal" data-toggle="modal" id="submitDelete">
                        <i class="fa fa-trash" aria-hidden="true"></i>
                    </button>
                </a>
                @endhasPermission
            </td>
        </tr>
    @endforeach
    @else
        <tr>
            <td colspan="7" style="text-align: center; color: red; font-size: 2rem">Not Found Data</td>
        </tr>
    @endif
    </tbody>
</table>
{{$users->links()}}

resources/views/admin/user/show.blade.php
<div class="modal fade" id="modal-form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Show User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">UserName</label>
                        <input type="text" class="form-control" value="{{$user->name}}" name="name" id="recipient-name" disabled>
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Image</label> <br>
                        <img src="{{ getImage($user->image) }}" alt=""
                             class="img-thumbnail img-circle">
                    </div>
                    <div class="form-group">
                        <label for="message-text" class="col-form-label">Email</label>
                        <input type="text" min="0" class="form-control" value="{{$user->email}}" name="email" id="recipient-name" disabled>
                    </div>
                    <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Gender</label>
                        @php
                            if ($user->gender == 0){
                                echo '<li>Male</li>';
                            }
                            else{
                                echo '<li>Female</li>';
                            }
                        @endphp
                        <br>
                    </div>

                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                    </div>
                </form>
            </div>

        </div>
    </div>
</div>